spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/gestao_vagas}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

security.token.secret=${SECURITY_TOKEN_SECRET:changeme-local}
security.token.secret.candidate=${SECURITY_TOKEN_SECRET_CANDIDATE:changeme-local-candidate}

management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.include=health,metrics,prometheus
management.endpoint.health.enabled=true
management.endpoint.health.show-details=always
management.endpoint.metrics.enabled=true
management.endpoint.prometheus.enabled=true